# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20886eb1ecba2d63a045373c94136e585f24fcf32e4fb05773f20c33493582185ba1603def789d5db9caef469ce5b7b2d7509b7693eccbf52234596299f2e283

test:
  secret_key_base: a6c81bdfeee7853b8930f103b0e5700d2217280c7e9f27be0813c7ea7ba038f8c2211ee4e65699c21697d620781e3d998441055f75996196aa29c523c0b39140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
